# Generated by Django 5.2.8 on 2025-12-05 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='quiz_app_question_unique_question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='video_url',
            field=models.URLField(),
        ),
    ]
